[tools]
usage = "latest"
node = "24.11.1"
go = "1.26.0"
neovim = "0.11.5"
python = "3.13.4"
uv = "0.9.8"
rust = "1.92.0"
"aqua:99designs/aws-vault" = "latest"
"aqua:BurntSushi/ripgrep" = "15.1.0"
"aqua:aws/aws-cli" = "2.7.22"
"aqua:bufbuild/buf" = "1.64.0"
"aqua:cli/cli" = "2.87.3"
"aqua:direnv/direnv" = "2.37.1"
"aqua:jesseduffield/lazygit" = "0.56.0"
"aqua:jqlang/jq" = "1.8.1"
"aqua:junegunn/fzf" = "0.67.0"
"aqua:metalbear-co/mirrord" = "3.182.0"
"aqua:peco/peco" = "0.5.11"
"aqua:starship/starship" = "1.24.0"
"cargo:sharkdp/fd" = "latest"
"go:github.com/nametake/golangci-lint-langserver" = "0.0.10"
"go:github.com/terraform-linters/tflint" = "0.60.0"
"go:golang.org/x/tools/cmd/goimports" = "0.30.0"
"go:golang.org/x/tools/gopls" = "0.20.0"
"go:github.com/golangci/golangci-lint/v2/cmd/golangci-lint" = "latest"
"go:github.com/matryer/moq" = "latest"
"npm:@openai/codex" = "latest"
"pipx:basedpyright" = "latest"
"vfox:mise-plugins/vfox-gcloud" = "552.0.0"
